
package Customer.View.Form.Admin_Form;

import Customer.Controller.Service.AdminBL;
import Customer.Model.AdminModel.MonAn;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import Customer.View.Main.Login_Form.FrmLogin;

/**
 *
 * @author DELL
 */
public class FrmManageFood extends javax.swing.JFrame {

    ArrayList<MonAn> lstFood = null;
    private DefaultTableModel dtm = null;

    public FrmManageFood() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);

        FrmLogin.addPlaceholderStyle(txtTimKiem);
        btnThemMonAn.grabFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlMenuBar = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lblQuanLyThucDon = new javax.swing.JLabel();
        lblQuanLyNhanSu = new javax.swing.JLabel();
        lblQuanLyDoanhThu = new javax.swing.JLabel();
        lblThongKeHoaDon = new javax.swing.JLabel();
        lblThongKeNhapKho = new javax.swing.JLabel();
        lblThongTinKhachHang = new javax.swing.JLabel();
        lblThongTinCaNhan = new javax.swing.JLabel();
        lblTaiKhoan = new javax.swing.JLabel();
        lblDangXuat = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        pnlMain = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtSLMonAn = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        btnThemMonAn = new javax.swing.JButton();
        btnSuaThongTin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMonAn = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cây Khế Restaurant");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/businessman.png"))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Cây Khế Administrator");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Restaurant");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/bell-boy.png"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/analytics (1).png"))); // NOI18N

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/menu (3).png"))); // NOI18N

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/inventory.png"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/receipt (2).png"))); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/customer (1).png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/10.png"))); // NOI18N

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user (2).png"))); // NOI18N

        lblQuanLyThucDon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblQuanLyThucDon.setText("Quản lý thực đơn");
        lblQuanLyThucDon.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblQuanLyThucDonMouseMoved(evt);
            }
        });
        lblQuanLyThucDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyThucDonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyThucDonMouseExited(evt);
            }
        });

        lblQuanLyNhanSu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblQuanLyNhanSu.setText("Quản lý nhân sự");
        lblQuanLyNhanSu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblQuanLyNhanSuMouseMoved(evt);
            }
        });
        lblQuanLyNhanSu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyNhanSuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyNhanSuMouseExited(evt);
            }
        });

        lblQuanLyDoanhThu.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblQuanLyDoanhThu.setText("Quản lý doanh thu");
        lblQuanLyDoanhThu.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblQuanLyDoanhThuMouseMoved(evt);
            }
        });
        lblQuanLyDoanhThu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblQuanLyDoanhThuMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblQuanLyDoanhThuMouseExited(evt);
            }
        });

        lblThongKeHoaDon.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblThongKeHoaDon.setText("Thống kê hóa đơn");
        lblThongKeHoaDon.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblThongKeHoaDonMouseMoved(evt);
            }
        });
        lblThongKeHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThongKeHoaDonMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThongKeHoaDonMouseExited(evt);
            }
        });

        lblThongKeNhapKho.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblThongKeNhapKho.setText("Thống kê kho nhập");
        lblThongKeNhapKho.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblThongKeNhapKhoMouseMoved(evt);
            }
        });
        lblThongKeNhapKho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThongKeNhapKhoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThongKeNhapKhoMouseExited(evt);
            }
        });

        lblThongTinKhachHang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblThongTinKhachHang.setText("Thông tin khách hàng");
        lblThongTinKhachHang.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblThongTinKhachHangMouseMoved(evt);
            }
        });
        lblThongTinKhachHang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblThongTinKhachHangMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThongTinKhachHangMouseExited(evt);
            }
        });

        lblThongTinCaNhan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblThongTinCaNhan.setText("Thông tin cá nhân");
        lblThongTinCaNhan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblThongTinCaNhanMouseMoved(evt);
            }
        });
        lblThongTinCaNhan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblThongTinCaNhanMouseExited(evt);
            }
        });

        lblTaiKhoan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTaiKhoan.setText("Tài khoản");
        lblTaiKhoan.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblTaiKhoanMouseMoved(evt);
            }
        });
        lblTaiKhoan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblTaiKhoanMouseExited(evt);
            }
        });

        lblDangXuat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblDangXuat.setText("Đăng xuất");
        lblDangXuat.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseMoved(evt);
            }
        });
        lblDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDangXuatMouseExited(evt);
            }
        });

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/user (3).png"))); // NOI18N

        javax.swing.GroupLayout pnlMenuBarLayout = new javax.swing.GroupLayout(pnlMenuBar);
        pnlMenuBar.setLayout(pnlMenuBarLayout);
        pnlMenuBarLayout.setHorizontalGroup(
            pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuBarLayout.createSequentialGroup()
                .addGroup(pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(pnlMenuBarLayout.createSequentialGroup()
                            .addGap(43, 43, 43)
                            .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuBarLayout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3))))
                        .addGroup(pnlMenuBarLayout.createSequentialGroup()
                            .addGap(78, 78, 78)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlMenuBarLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addGroup(pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel15)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(lblQuanLyThucDon)
                            .addComponent(lblQuanLyNhanSu)
                            .addGroup(pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lblThongKeHoaDon)
                                .addComponent(lblQuanLyDoanhThu))
                            .addGroup(pnlMenuBarLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblThongTinKhachHang)
                                    .addComponent(lblThongKeNhapKho)
                                    .addComponent(lblThongTinCaNhan)
                                    .addComponent(lblTaiKhoan)
                                    .addComponent(lblDangXuat))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlMenuBarLayout.setVerticalGroup(
            pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnlMenuBarLayout.createSequentialGroup()
                        .addGroup(pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMenuBarLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel2))
                            .addComponent(lblIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMenuBarLayout.createSequentialGroup()
                                .addGap(37, 37, 37)
                                .addComponent(lblQuanLyThucDon)
                                .addGap(16, 16, 16))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuBarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnlMenuBarLayout.createSequentialGroup()
                                .addGroup(pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlMenuBarLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(lblQuanLyNhanSu)
                                        .addGap(18, 18, 18)
                                        .addGroup(pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblQuanLyDoanhThu)))
                                    .addGroup(pnlMenuBarLayout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(32, 32, 32)
                                .addComponent(lblThongKeHoaDon))
                            .addGroup(pnlMenuBarLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(30, 30, 30)
                        .addComponent(lblThongKeNhapKho)
                        .addGap(8, 8, 8))
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuBarLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlMenuBarLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(lblThongTinKhachHang)))
                .addGap(55, 55, 55)
                .addGroup(pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblThongTinCaNhan)
                    .addComponent(jLabel15))
                .addGroup(pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMenuBarLayout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(lblTaiKhoan)
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMenuBarLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(pnlMenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDangXuat))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/menu (3).png"))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel12.setText("Quản lý thực đơn");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel13.setText("Số món ăn đang kinh doanh");

        txtSLMonAn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtSLMonAn.setEnabled(false);

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Danh sách món ăn");

        txtTimKiem.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        txtTimKiem.setText("Tìm kiếm món ăn...");
        txtTimKiem.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtTimKiemFocusLost(evt);
            }
        });
        txtTimKiem.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTimKiemKeyPressed(evt);
            }
        });

        btnThemMonAn.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnThemMonAn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/food.png"))); // NOI18N
        btnThemMonAn.setText("Thêm món ăn");
        btnThemMonAn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemMonAnActionPerformed(evt);
            }
        });

        btnSuaThongTin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        btnSuaThongTin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/change.png"))); // NOI18N
        btnSuaThongTin.setText("Sửa thông tin");
        btnSuaThongTin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaThongTinActionPerformed(evt);
            }
        });

        tblMonAn.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        tblMonAn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã MA", "Tên món ăn", "Đơn giá", "Loại món", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblMonAn);

        javax.swing.GroupLayout pnlMainLayout = new javax.swing.GroupLayout(pnlMain);
        pnlMain.setLayout(pnlMainLayout);
        pnlMainLayout.setHorizontalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(36, 36, 36)
                                .addComponent(txtSLMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnlMainLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel12)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator1)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlMainLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlMainLayout.createSequentialGroup()
                        .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnThemMonAn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSuaThongTin)))
                .addGap(3, 3, 3))
        );
        pnlMainLayout.setVerticalGroup(
            pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12))
                .addGap(26, 26, 26)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtSLMonAn)
                    .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThemMonAn, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSuaThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMenuBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMenuBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        lstFood = AdminBL.getListFood();
        dtm = (DefaultTableModel) tblMonAn.getModel();
        for (MonAn food : lstFood) {
            dtm.addRow(new Object[]{food.getMaMA(), food.getTenMA(), food.getDonGia(), food.getLoaiMon(), food.getTrangThai()});
        }
        tblMonAn.setRowHeight(50);
        tblMonAn.getColumnModel().getColumn(0).setMaxWidth(100);
        JTableHeader hearder = tblMonAn.getTableHeader();
        hearder.setFont(new Font("Arial", Font.BOLD, 20));

        txtSLMonAn.setText("" + lstFood.size());


    }//GEN-LAST:event_formWindowOpened

    private void txtTimKiemFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusGained
        // TODO add your handling code here:
        if (txtTimKiem.getText().equals("Tìm kiếm món ăn...")) {
            txtTimKiem.setText("");
            txtTimKiem.requestFocus();
            FrmLogin.removePlaceholderStyle(txtTimKiem);
        }
    }//GEN-LAST:event_txtTimKiemFocusGained

    private void txtTimKiemFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtTimKiemFocusLost
        // TODO add your handling code here:
        if (txtTimKiem.getText().length() == 0) {
            txtTimKiem.setText("Tìm kiếm món ăn...");
            FrmLogin.addPlaceholderStyle(txtTimKiem);
        }
    }//GEN-LAST:event_txtTimKiemFocusLost

    private void txtTimKiemKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTimKiemKeyPressed
        // TODO add your handling code here
        dtm = new DefaultTableModel();
        dtm.addColumn("Mã MA");
        dtm.addColumn("Tên món ăn");
        dtm.addColumn("Đơn giá");
        dtm.addColumn("Loại món");
        dtm.addColumn("Loại món");
        lstFood = AdminBL.getFilterFood(txtTimKiem.getText());
        for (MonAn food : lstFood) {
            dtm.addRow(new Object[]{food.getMaMA(), food.getTenMA(), food.getDonGia(), food.getLoaiMon(), food.getTrangThai()});
        }
        tblMonAn.setModel(dtm);
    }//GEN-LAST:event_txtTimKiemKeyPressed

    private void lblQuanLyThucDonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyThucDonMouseMoved
        // TODO add your handling code here:
        lblQuanLyThucDon.setForeground(Color.white);
        lblQuanLyThucDon.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblQuanLyThucDonMouseMoved

    private void lblQuanLyThucDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyThucDonMouseExited
        // TODO add your handling code here:
        lblQuanLyThucDon.setForeground(Color.black);
    }//GEN-LAST:event_lblQuanLyThucDonMouseExited

    private void lblQuanLyNhanSuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyNhanSuMouseMoved
        // TODO add your handling code here:
        lblQuanLyNhanSu.setForeground(Color.white);
        lblQuanLyNhanSu.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblQuanLyNhanSuMouseMoved

    private void lblQuanLyNhanSuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyNhanSuMouseExited
        // TODO add your handling code here:
        lblQuanLyNhanSu.setForeground(Color.black);
    }//GEN-LAST:event_lblQuanLyNhanSuMouseExited

    private void lblQuanLyDoanhThuMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyDoanhThuMouseMoved
        // TODO add your handling code here:
        lblQuanLyDoanhThu.setForeground(Color.white);
        lblQuanLyDoanhThu.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblQuanLyDoanhThuMouseMoved

    private void lblQuanLyDoanhThuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyDoanhThuMouseExited
        // TODO add your handling code here:
        lblQuanLyDoanhThu.setForeground(Color.black);
    }//GEN-LAST:event_lblQuanLyDoanhThuMouseExited

    private void lblThongKeHoaDonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeHoaDonMouseMoved
        // TODO add your handling code here:
        lblThongKeHoaDon.setForeground(Color.white);
        lblThongKeHoaDon.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblThongKeHoaDonMouseMoved

    private void lblThongKeHoaDonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeHoaDonMouseExited
        // TODO add your handling code here:
        lblThongKeHoaDon.setForeground(Color.black);
    }//GEN-LAST:event_lblThongKeHoaDonMouseExited

    private void lblThongKeNhapKhoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeNhapKhoMouseMoved
        // TODO add your handling code here:
        lblThongKeNhapKho.setForeground(Color.white);
        lblThongKeNhapKho.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblThongKeNhapKhoMouseMoved

    private void lblThongKeNhapKhoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeNhapKhoMouseExited
        // TODO add your handling code here:
        lblThongKeNhapKho.setForeground(Color.black);
    }//GEN-LAST:event_lblThongKeNhapKhoMouseExited

    private void lblThongTinKhachHangMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongTinKhachHangMouseMoved
        // TODO add your handling code here:
        lblThongTinKhachHang.setForeground(Color.white);
        lblThongTinKhachHang.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblThongTinKhachHangMouseMoved

    private void lblThongTinKhachHangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongTinKhachHangMouseExited
        // TODO add your handling code here:
        lblThongTinKhachHang.setForeground(Color.black);
    }//GEN-LAST:event_lblThongTinKhachHangMouseExited

    private void lblThongTinCaNhanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongTinCaNhanMouseMoved
        // TODO add your handling code here:
        lblThongTinCaNhan.setForeground(Color.white);
        lblThongTinCaNhan.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblThongTinCaNhanMouseMoved

    private void lblThongTinCaNhanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongTinCaNhanMouseExited
        // TODO add your handling code here:
        lblThongTinCaNhan.setForeground(Color.black);
    }//GEN-LAST:event_lblThongTinCaNhanMouseExited

    private void lblTaiKhoanMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTaiKhoanMouseMoved
        // TODO add your handling code here:
        lblTaiKhoan.setForeground(Color.white);
        lblTaiKhoan.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblTaiKhoanMouseMoved

    private void lblTaiKhoanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTaiKhoanMouseExited
        // TODO add your handling code here:
        lblTaiKhoan.setForeground(Color.black);
    }//GEN-LAST:event_lblTaiKhoanMouseExited

    private void lblDangXuatMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseMoved
        // TODO add your handling code here:
        lblDangXuat.setForeground(Color.white);
        lblDangXuat.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lblDangXuatMouseMoved

    private void lblDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseExited
        // TODO add your handling code here:
        lblDangXuat.setForeground(Color.black);
    }//GEN-LAST:event_lblDangXuatMouseExited

    private void lblQuanLyThucDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyThucDonMouseClicked
        // TODO add your handling code here:
        FrmManageFood frm = new FrmManageFood();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblQuanLyThucDonMouseClicked

    private void lblDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDangXuatMouseClicked
        // TODO add your handling code here:
        int approve = JOptionPane.showConfirmDialog(this, "Bạn thật sự muốn thoát?", "Đăng xuất", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (approve == JOptionPane.YES_OPTION) {
            this.setVisible(false);
            FrmLogin frm = new FrmLogin();
            frm.setVisible(true);
        }
    }//GEN-LAST:event_lblDangXuatMouseClicked

    private void btnThemMonAnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemMonAnActionPerformed
        // TODO add your handling code here:
        FrmAddFood frm = new FrmAddFood();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnThemMonAnActionPerformed

    private void lblQuanLyNhanSuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyNhanSuMouseClicked
        // TODO add your handling code here:
        FrmManageStaff frm = new FrmManageStaff();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblQuanLyNhanSuMouseClicked

    private void btnSuaThongTinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaThongTinActionPerformed
        // TODO add your handling code here:
        FrmEditFood frm = new FrmEditFood();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnSuaThongTinActionPerformed

    private void lblThongKeHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeHoaDonMouseClicked
        // TODO add your handling code here:
        FrmStatistBill frm = new FrmStatistBill();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblThongKeHoaDonMouseClicked

    private void lblThongKeNhapKhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongKeNhapKhoMouseClicked
        // TODO add your handling code here:
        FrmImportBill frm = new FrmImportBill();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblThongKeNhapKhoMouseClicked

    private void lblQuanLyDoanhThuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblQuanLyDoanhThuMouseClicked
        // TODO add your handling code here:
        FrmReportRevenue frm = new FrmReportRevenue();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblQuanLyDoanhThuMouseClicked

    private void lblThongTinKhachHangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblThongTinKhachHangMouseClicked
        // TODO add your handling code here:
        FrmManagerCustomer frm = new FrmManagerCustomer();
        frm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblThongTinKhachHangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmManageFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmManageFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmManageFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmManageFood.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmManageFood().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSuaThongTin;
    private javax.swing.JButton btnThemMonAn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblDangXuat;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblQuanLyDoanhThu;
    private javax.swing.JLabel lblQuanLyNhanSu;
    private javax.swing.JLabel lblQuanLyThucDon;
    private javax.swing.JLabel lblTaiKhoan;
    private javax.swing.JLabel lblThongKeHoaDon;
    private javax.swing.JLabel lblThongKeNhapKho;
    private javax.swing.JLabel lblThongTinCaNhan;
    private javax.swing.JLabel lblThongTinKhachHang;
    private javax.swing.JPanel pnlMain;
    private javax.swing.JPanel pnlMenuBar;
    private javax.swing.JTable tblMonAn;
    private javax.swing.JTextField txtSLMonAn;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
